environment:
  matrix:
  # node.js
  - nodejs_version: "6"
  # io.js
  - nodejs_version: "1.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  # run tests
  - npm test

build: off
